version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  simple:
    format: "%(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/backend.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  # 根日志记录器
  "":
    level: INFO
    handlers: [console, file, error_file]
    propagate: true

  # FastAPI 日志
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

  # 应用日志
  app:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  # 监控服务日志
  app.services.monitor_service:
    level: INFO
    handlers: [console, file]
    propagate: false

  # API 日志
  app.api:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  # WebSocket 日志
  app.api.monitor:
    level: INFO
    handlers: [console, file]
    propagate: false